import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "../../../lib/supabase/server";
import styles from "../trade-review.module.css";

export const dynamic="force-dynamic";
const pretty=(v:string|number|null|undefined)=>v==null||v===""?"—":String(v).replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const dt=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Chicago",timeZoneName:"short"}).format(new Date(v)):"—";

export default async function TradeReviewToolPage(){
 const supabase=await createClient(); const {data:c,error:ce}=await supabase.auth.getClaims(); if(ce||!c?.claims)redirect("/login"); const {data:a,error:ae}=await supabase.rpc("is_trading_research_web_user"); if(ae||a!==true)redirect("/unauthorized");
 const {data:strategy,error:strategyError}=await supabase.from("strategies").select("strategy_id,strategy_code,strategy_name,strategy_type,status,description,baseline_model").eq("strategy_code","TRADE_REVIEW").maybeSingle();
 if(strategyError)throw strategyError; if(!strategy)notFound();
 const [sr,phr,dr,br]=await Promise.all([
  supabase.from("project_state").select("strategy_id,active_phase_code,active_phase_name,next_phase_code,next_phase_name,blocker_count,baseline_model,baseline_status,last_decision,roadmap_version,metadata_json,updated_at").eq("strategy_id",strategy.strategy_id).maybeSingle(),
  supabase.from("program_phases").select("phase_id,phase_code,phase_name,objective,status,sequence_order,entry_criteria,exit_criteria,started_at,completed_at,next_phase_code,notes,updated_at").eq("strategy_id",strategy.strategy_id).order("sequence_order"),
  supabase.from("project_decisions").select("decision_id,decision_date,title,decision,rationale,evidence,affects_model_version,status").eq("strategy_id",strategy.strategy_id).order("decision_date",{ascending:false}).limit(20),
  supabase.from("project_backlog").select("backlog_id,title,description,category,priority,status,origin_phase,blocking_current_phase,why_it_matters,promoted_to_phase,created_at,resolved_at,updated_at").eq("strategy_id",strategy.strategy_id).order("priority").order("created_at",{ascending:false})
 ]);
 const error=sr.error||phr.error||dr.error||br.error; const state=sr.data; const phases=phr.data??[]; const decisions=dr.data??[]; const backlog=br.data??[]; const openBacklog=backlog.filter(x=>!["complete","rejected","cancelled"].includes(x.status));
 return <main className={styles.tradeTheme}><section className={`projectHero ${styles.hero}`}><div><Link className="backLink" href="/dashboard#trade-reviews-analysis">← Trade Reviews and Analysis</Link><p className={`eyebrow ${styles.accent}`}>PROJECT · DEVELOPMENT</p><h1>Trade Review &amp; Analysis Tool</h1><p className="lede">How we are building and improving the system that analyzes reviewed trades.</p><p className="sectionDescription">Shared system, separate development experience · Read-only project-management view</p></div><Link className="projectLink" href="/dashboard/trade_review">Open My Trade Reviews →</Link></section>
 {error?<section className="alertPanel"><strong>Tool project query failed.</strong><span>{error.message}</span></section>:<>
 <nav className={`projectNav ${styles.nav}`}><a href="#status">Status</a><a href="#roadmap">Roadmap</a><a href="#decisions">Decisions</a><a href="#backlog">Backlog</a><a href="#methodology">Methodology</a></nav>
 <section id="status" className="metricGrid"><article className="metricCard"><span>Current Phase</span><strong className="metricText">{state?.active_phase_code??"—"}</strong><small>{state?.active_phase_name??"Not tracked"}</small></article><article className="metricCard"><span>Next Phase</span><strong className="metricText">{state?.next_phase_code??"—"}</strong><small>{state?.next_phase_name??"Not scheduled"}</small></article><article className="metricCard"><span>Roadmap</span><strong className="metricText">{state?.roadmap_version??"—"}</strong><small>Current tracked roadmap</small></article><article className="metricCard"><span>Open Backlog</span><strong>{openBacklog.length}</strong><small>{openBacklog.filter(x=>x.blocking_current_phase).length} blocking current phase</small></article></section>
 <section className="projectSection"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>CURRENT PROJECT STATE</p><h2>{state?.active_phase_code??"—"} · {state?.active_phase_name??"Not tracked"}</h2></div><span>Updated {dt(state?.updated_at)}</span></div><div className="statusPlanGrid"><article className="detailPanel"><span className="fieldLabel">Latest recorded decision</span><p>{state?.last_decision??"No project-state decision summary recorded."}</p><dl className="detailGrid"><div><dt>Baseline</dt><dd>{state?.baseline_model??strategy.baseline_model??"Not set"}</dd></div><div><dt>Baseline status</dt><dd>{pretty(state?.baseline_status)}</dd></div><div><dt>Blockers</dt><dd>{state?.blocker_count??0}</dd></div></dl></article><article className="detailPanel"><span className="fieldLabel">System relationship</span><p>The Tool creates review capabilities. Reviewed trades create evidence and findings. Those findings feed methodology, feature development, research hypotheses, and future Tool improvements.</p><strong>TRADE → REVIEW → EVIDENCE → FINDING → PATTERN → TOOL / RESEARCH IMPROVEMENT</strong></article></div></section>
 <section className="projectSection" id="roadmap"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>ROADMAP</p><h2>Development phases</h2></div><span>{phases.length} tracked phases</span></div><div className="stackList">{phases.length?phases.map(p=><article className="detailPanel" key={p.phase_id}><div className="listTop"><strong>{p.phase_code} · {p.phase_name}</strong><span className="statusPill">{pretty(p.status)}</span></div><p>{p.objective??"No objective recorded."}</p><div className={styles.sessionStats}><span>Sequence {p.sequence_order}</span><span>Started: {dt(p.started_at)}</span><span>Completed: {dt(p.completed_at)}</span>{p.next_phase_code&&<span>Next: {p.next_phase_code}</span>}</div>{p.exit_criteria&&<details><summary>Exit criteria</summary><p>{p.exit_criteria}</p></details>}</article>):<p className="emptyState">No roadmap phases recorded.</p>}</div></section>
 <section className="projectSection twoColumnSection"><div id="decisions"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>DECISIONS</p><h2>Project decisions</h2></div></div><div className="stackList">{decisions.length?decisions.map(d=><article className="detailPanel" key={d.decision_id}><div className="listTop"><strong>{d.title}</strong><time>{dt(d.decision_date)}</time></div><p>{d.decision}</p>{d.rationale&&<small>{d.rationale}</small>}</article>):<p className="emptyState">No decisions recorded.</p>}</div></div><div id="backlog"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>BACKLOG</p><h2>Development queue</h2></div></div><div className="stackList">{backlog.length?backlog.map(b=><article className={`detailPanel${b.blocking_current_phase&&!["complete","rejected","cancelled"].includes(b.status)?" blockingPanel":""}`} key={b.backlog_id}><div className="listTop"><strong>{b.title}</strong><span className="statusPill">{pretty(b.status)}</span></div><p>{b.description??b.why_it_matters??"No description recorded."}</p><small>{b.category?`${pretty(b.category)} · `:""}{b.priority!=null?`Priority ${b.priority} · `:""}{b.origin_phase?`Origin ${b.origin_phase}`:""}</small></article>):<p className="emptyState">No backlog items recorded.</p>}</div></div></section>
 <section className="projectSection" id="methodology"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>METHODOLOGY &amp; ENGINES</p><h2>Development responsibilities</h2></div><span>Database-backed project state</span></div><div className={styles.researchGrid}><article className="detailPanel"><strong>Trade Health Engine</strong><p>Development of real-time and retrospective trade-health evidence, expected-response failure, continuation, recovery and risk-state logic as persisted project work supports it.</p></article><article className="detailPanel"><strong>Event Engine</strong><p>Timestamped market/trade events and compact evidence markers such as VWAP state, momentum, structure and acceptance/rejection behavior.</p></article><article className="detailPanel"><strong>Trader Development Engine</strong><p>Evidence maturity, strengths, improvement priorities, corrective principles and longitudinal improvement/regression measurement.</p></article><article className="detailPanel"><strong>Research Infrastructure</strong><p>Data contracts, indicator registry, review methodology, feature development and implementation status remain governed through the project-management records above.</p></article></div></section>
 </>}</main>;
}
