import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "../../../lib/supabase/server";
import styles from "../trade-review.module.css";
export const dynamic="force-dynamic";
type Props={params:Promise<{tradeId:string}>};
const pretty=(v:string|null|undefined)=>v?String(v).replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()):"—";
const pct=(v:number|null|undefined)=>v==null?"—":`${v>0?"+":""}${Number(v).toFixed(3)}%`;
const dt=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Chicago",timeZoneName:"short"}).format(new Date(v)):"—";
const duration=(s:number|null)=>s==null?"—":s<3600?`${Math.round(s/60)} minutes`:`${Math.floor(s/3600)}h ${Math.round((s%3600)/60)}m`;
export default async function TradeDetail({params}:Props){
 const {tradeId}=await params,supabase=await createClient(); const {data:c,error:ce}=await supabase.auth.getClaims(); if(ce||!c?.claims)redirect("/login"); const {data:a,error:ae}=await supabase.rpc("is_trading_research_web_user");if(ae||a!==true)redirect("/unauthorized");
 const [tr,fr,er]=await Promise.all([supabase.from("trade_reviews").select("*").eq("trade_review_id",tradeId).maybeSingle(),supabase.from("trade_review_findings").select("*").eq("trade_review_id",tradeId).order("created_at"),supabase.from("trader_profile_evidence").select("profile_evidence_id,profile_item_id,evidence_direction,evidence_note,evidence_weight,trader_profile_items(name,polarity,evidence_state,corrective_principle)").eq("trade_review_id",tradeId)]);
 if(tr.error)throw tr.error;if(!tr.data)notFound(); const t=tr.data,findings=fr.data??[],profileEvidence=er.data??[]; const meta=(t.metadata_json??{}) as Record<string,unknown>;
 const metaEntries=Object.entries(meta).filter(([,v])=>v!==null&&v!==""&&typeof v!=="object");
 return <main className={styles.tradeTheme}><section className={`projectHero ${styles.hero}`}><div><Link className="backLink" href="/dashboard/trade_review">← Trade Review & Trader Development</Link><p className={`eyebrow ${styles.accent}`}>TRADE #{String(t.trade_number??"").padStart(3,"0")} · {t.strategy_version}</p><h1>{t.symbol} · {pretty(t.direction)}</h1><p className="lede">{t.executive_summary??t.trader_outcome??"Completed trade review"}</p><p className="sectionDescription">{t.trade_date} · {pretty(t.review_status)} · Retrospective review</p></div><span className={`securityBadge ${(t.realized_pnl_pct??0)>=0?styles.positive:styles.negative}`}>{pct(t.realized_pnl_pct)} realized</span></section>
 <nav className={`projectNav ${styles.nav}`}><a href="#snapshot">Snapshot</a><a href="#review">Review</a><a href="#findings">Findings</a><a href="#profile-evidence">Profile Evidence</a><a href="#metadata">Recorded Evidence</a></nav>
 <section id="snapshot" className="metricGrid"><article className="metricCard"><span>Realized P&amp;L</span><strong className={(t.realized_pnl_pct??0)>=0?styles.positive:styles.negative}>{pct(t.realized_pnl_pct)}</strong><small>Canonical percentage return</small></article><article className="metricCard"><span>Setup Grade</span><strong>{t.signal_grade??"—"}</strong><small>{t.strategy_version}</small></article><article className="metricCard"><span>Holding Duration</span><strong className="metricText">{duration(t.holding_seconds)}</strong><small>{dt(t.entry_time)} → {dt(t.exit_time)}</small></article><article className="metricCard"><span>Planned Risk / Target</span><strong className="metricText">{pct(t.planned_loss_pct)} / {pct(t.planned_profit_pct)}</strong><small>{t.planned_trade_type??"Plan not recorded"}</small></article></section>
 <section className="projectSection" id="review"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>EXECUTIVE REVIEW</p><h2>Strategy opportunity vs trader result</h2></div></div><div className="statusPlanGrid"><article className="detailPanel"><span className="fieldLabel">Strategy Outcome</span><p>{t.strategy_outcome??t.benchmark_outcome??"Not recorded."}</p></article><article className="detailPanel"><span className="fieldLabel">Trader Outcome</span><p>{t.trader_outcome??"Not recorded."}</p></article><article className="detailPanel"><span className="fieldLabel">Entry Rationale</span><p>{t.entry_rationale??"Not populated."}</p><dl className="detailGrid"><div><dt>Entry</dt><dd>{dt(t.entry_time)}</dd></div><div><dt>Price</dt><dd>{t.entry_price??"—"}</dd></div></dl></article><article className="detailPanel"><span className="fieldLabel">Exit Rationale</span><p>{t.exit_rationale??"Not populated."}</p><dl className="detailGrid"><div><dt>Exit</dt><dd>{dt(t.exit_time)}</dd></div><div><dt>Price</dt><dd>{t.exit_price??"—"}</dd></div></dl></article></div><article className={`detailPanel ${styles.profileCard}`} style={{marginTop:18}}><span className="fieldLabel">Trade Lesson</span><h3>{t.key_lesson??"No lesson populated."}</h3></article></section>
 <section className="projectSection" id="findings"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>SUPPORTING FINDINGS</p><h2>Evidence generated by this trade</h2></div><span>{findings.length} findings</span></div><div className={styles.findingsGrid}>{findings.length?findings.map(f=><article className="detailPanel" key={f.finding_id}><div className="listTop"><strong>{f.title}</strong><span className="statusPill">{pretty(f.evidence_state)}</span></div><small>{pretty(f.category)} · {pretty(f.research_status)}{f.realtime_available===true?" · Available in real time":f.realtime_available===false?" · Retrospective":""}</small><p>{f.finding}</p>{Array.isArray(f.tags)&&f.tags.length>0&&<small>{f.tags.join(" · ")}</small>}</article>):<p className="emptyState">No trade-specific findings recorded.</p>}</div></section>
 <section className="projectSection" id="profile-evidence"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>TRADER PROFILE EVIDENCE</p><h2>How this trade affects the developing profile</h2></div><span>{profileEvidence.length} links</span></div><div className="stackList">{profileEvidence.length?profileEvidence.map((e:any)=><article className="detailPanel" key={e.profile_evidence_id}><div className="listTop"><strong>{e.trader_profile_items?.name??"Profile observation"}</strong><span className="statusPill">{pretty(e.trader_profile_items?.evidence_state)}</span></div><small>{pretty(e.evidence_direction)} evidence{e.evidence_weight!=null?` · weight ${e.evidence_weight}`:""}</small><p>{e.evidence_note}</p>{e.trader_profile_items?.corrective_principle&&<p className={styles.principle}>{e.trader_profile_items.corrective_principle}</p>}</article>):<p className="emptyState">This trade is not yet linked to a Trader Profile observation.</p>}</div></section>
 <section className="projectSection" id="metadata"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>RECORDED EVIDENCE</p><h2>Additional structured review context</h2></div></div><article className="detailPanel">{metaEntries.length?<dl className="detailGrid">{metaEntries.map(([k,v])=><div key={k}><dt>{pretty(k)}</dt><dd>{typeof v==="boolean"?(v?"Yes":"No"):String(v)}</dd></div>)}</dl>:<p>No additional scalar metadata recorded.</p>}</article></section>
 </main>;
}