-- FTHC Historical Staging Table V1
-- Temporary raw landing table for the 2,457-event canonical master.
create table if not exists public.fthc_historical_staging_v1 (
    staging_id bigint generated always as identity primary key,
    "set" text, -- source: Set
    "symbol" text, -- source: Symbol
    "time" text, -- source: time
    "open" text, -- source: open
    "high" text, -- source: high
    "low" text, -- source: low
    "close" text, -- source: close
    "bullish_research_event" text, -- source: Bullish Research Event
    "bearish_research_event" text, -- source: Bearish Research Event
    "fthc_eventdatekey" text, -- source: FTHC_EventDateKey
    "fthc_eventtimestamp" text, -- source: FTHC_EventTimestamp
    "fthc_direction" text, -- source: FTHC_Direction
    "fthc_researchevent" text, -- source: FTHC_ResearchEvent
    "fthc_productionsignal" text, -- source: FTHC_ProductionSignal
    "fthc_referenceprice" text, -- source: FTHC_ReferencePrice
    "fthc_c1_open" text, -- source: FTHC_C1_Open
    "fthc_c1_high" text, -- source: FTHC_C1_High
    "fthc_c1_low" text, -- source: FTHC_C1_Low
    "fthc_c1_close" text, -- source: FTHC_C1_Close
    "fthc_c1_volume" text, -- source: FTHC_C1_Volume
    "fthc_c1_tr" text, -- source: FTHC_C1_TR
    "fthc_c1_vwap" text, -- source: FTHC_C1_VWAP
    "fthc_c2_open" text, -- source: FTHC_C2_Open
    "fthc_c2_high" text, -- source: FTHC_C2_High
    "fthc_c2_low" text, -- source: FTHC_C2_Low
    "fthc_c2_close" text, -- source: FTHC_C2_Close
    "fthc_c2_volume" text, -- source: FTHC_C2_Volume
    "fthc_c2_tr" text, -- source: FTHC_C2_TR
    "fthc_c2_vwap" text, -- source: FTHC_C2_VWAP
    "fthc_c1_relvol" text, -- source: FTHC_C1_RelVol
    "fthc_c2_relvol" text, -- source: FTHC_C2_RelVol
    "fthc_combined_relvol" text, -- source: FTHC_Combined_RelVol
    "fthc_atr_selected" text, -- source: FTHC_ATR_Selected
    "fthc_atr_prevdaily" text, -- source: FTHC_ATR_PrevDaily
    "fthc_atr_prevday1m" text, -- source: FTHC_ATR_PrevDay1M
    "fthc_atr_prev5day1m" text, -- source: FTHC_ATR_Prev5Day1M
    "fthc_atr_first2" text, -- source: FTHC_ATR_First2
    "fthc_vwap_distance" text, -- source: FTHC_VWAP_Distance
    "fthc_deltapct" text, -- source: FTHC_DeltaPct
    "fthc_pmh" text, -- source: FTHC_PMH
    "fthc_pml" text, -- source: FTHC_PML
    "fthc_pm_open" text, -- source: FTHC_PM_Open
    "fthc_pm_last" text, -- source: FTHC_PM_Last
    "fthc_pm_volume" text, -- source: FTHC_PM_Volume
    "fthc_ah_high" text, -- source: FTHC_AH_High
    "fthc_ah_low" text, -- source: FTHC_AH_Low
    "fthc_ah_volume" text, -- source: FTHC_AH_Volume
    "fthc_pdh" text, -- source: FTHC_PDH
    "fthc_pdl" text, -- source: FTHC_PDL
    "fthc_prevrthclose" text, -- source: FTHC_PrevRTHClose
    "fthc_outcome_050v050" text, -- source: FTHC_Outcome_050v050
    "fthc_outcome_100v050" text, -- source: FTHC_Outcome_100v050
    "fthc_minutesto_025" text, -- source: FTHC_MinutesTo_025
    "fthc_minutesto_050" text, -- source: FTHC_MinutesTo_050
    "fthc_minutesto_075" text, -- source: FTHC_MinutesTo_075
    "fthc_minutesto_100" text, -- source: FTHC_MinutesTo_100
    "fthc_minutesto_adverse050" text, -- source: FTHC_MinutesTo_Adverse050
    "fthc_final_mfe" text, -- source: FTHC_Final_MFE
    "fthc_final_mae" text, -- source: FTHC_Final_MAE
    "fthc_cp1_mfe" text, -- source: FTHC_CP1_MFE
    "fthc_cp1_mae" text, -- source: FTHC_CP1_MAE
    "fthc_cp2_mfe" text, -- source: FTHC_CP2_MFE
    "fthc_cp2_mae" text, -- source: FTHC_CP2_MAE
    "fthc_cp3_mfe" text, -- source: FTHC_CP3_MFE
    "fthc_cp3_mae" text, -- source: FTHC_CP3_MAE
    "fthc_cp5_mfe" text, -- source: FTHC_CP5_MFE
    "fthc_cp5_mae" text, -- source: FTHC_CP5_MAE
    "fthc_cp10_mfe" text, -- source: FTHC_CP10_MFE
    "fthc_cp10_mae" text, -- source: FTHC_CP10_MAE
    "volume" text, -- source: Volume
    "volume_ma" text, -- source: Volume MA
    "fths_eventdatekey" text, -- source: FTHS_EventDateKey
    "fths_eventtimestamp" text, -- source: FTHS_EventTimestamp
    "fths_direction" text, -- source: FTHS_Direction
    "fths_cp1_pm_state" text, -- source: FTHS_CP1_PM_State
    "fths_cp1_ah_state" text, -- source: FTHS_CP1_AH_State
    "fths_cp1_pd_state" text, -- source: FTHS_CP1_PD_State
    "fths_cp1_levelsretained" text, -- source: FTHS_CP1_LevelsRetained
    "fths_cp1_minlevelsretained" text, -- source: FTHS_CP1_MinLevelsRetained
    "fths_cp2_pm_state" text, -- source: FTHS_CP2_PM_State
    "fths_cp2_ah_state" text, -- source: FTHS_CP2_AH_State
    "fths_cp2_pd_state" text, -- source: FTHS_CP2_PD_State
    "fths_cp2_levelsretained" text, -- source: FTHS_CP2_LevelsRetained
    "fths_cp2_minlevelsretained" text, -- source: FTHS_CP2_MinLevelsRetained
    "fths_cp3_pm_state" text, -- source: FTHS_CP3_PM_State
    "fths_cp3_ah_state" text, -- source: FTHS_CP3_AH_State
    "fths_cp3_pd_state" text, -- source: FTHS_CP3_PD_State
    "fths_cp3_levelsretained" text, -- source: FTHS_CP3_LevelsRetained
    "fths_cp3_minlevelsretained" text, -- source: FTHS_CP3_MinLevelsRetained
    "fths_cp5_pm_state" text, -- source: FTHS_CP5_PM_State
    "fths_cp5_ah_state" text, -- source: FTHS_CP5_AH_State
    "fths_cp5_pd_state" text, -- source: FTHS_CP5_PD_State
    "fths_cp5_levelsretained" text, -- source: FTHS_CP5_LevelsRetained
    "fths_cp5_minlevelsretained" text, -- source: FTHS_CP5_MinLevelsRetained
    "fths_cp10_pm_state" text, -- source: FTHS_CP10_PM_State
    "fths_cp10_ah_state" text, -- source: FTHS_CP10_AH_State
    "fths_cp10_pd_state" text, -- source: FTHS_CP10_PD_State
    "fths_cp10_levelsretained" text, -- source: FTHS_CP10_LevelsRetained
    "fths_cp10_minlevelsretained" text, -- source: FTHS_CP10_MinLevelsRetained
    "fths_cp1_pm_lost" text, -- source: FTHS_CP1_PM_Lost
    "fths_cp1_pm_reclaimed" text, -- source: FTHS_CP1_PM_Reclaimed
    "fths_cp1_ah_lost" text, -- source: FTHS_CP1_AH_Lost
    "fths_cp1_ah_reclaimed" text, -- source: FTHS_CP1_AH_Reclaimed
    "fths_cp1_pd_lost" text, -- source: FTHS_CP1_PD_Lost
    "fths_cp1_pd_reclaimed" text, -- source: FTHS_CP1_PD_Reclaimed
    "fths_cp2_pm_lost" text, -- source: FTHS_CP2_PM_Lost
    "fths_cp2_pm_reclaimed" text, -- source: FTHS_CP2_PM_Reclaimed
    "fths_cp2_ah_lost" text, -- source: FTHS_CP2_AH_Lost
    "fths_cp2_ah_reclaimed" text, -- source: FTHS_CP2_AH_Reclaimed
    "fths_cp2_pd_lost" text, -- source: FTHS_CP2_PD_Lost
    "fths_cp2_pd_reclaimed" text, -- source: FTHS_CP2_PD_Reclaimed
    "fths_cp3_pm_lost" text, -- source: FTHS_CP3_PM_Lost
    "fths_cp3_pm_reclaimed" text, -- source: FTHS_CP3_PM_Reclaimed
    "fths_cp3_ah_lost" text, -- source: FTHS_CP3_AH_Lost
    "fths_cp3_ah_reclaimed" text, -- source: FTHS_CP3_AH_Reclaimed
    "fths_cp3_pd_lost" text, -- source: FTHS_CP3_PD_Lost
    "fths_cp3_pd_reclaimed" text, -- source: FTHS_CP3_PD_Reclaimed
    "fths_cp5_pm_lost" text, -- source: FTHS_CP5_PM_Lost
    "fths_cp5_pm_reclaimed" text, -- source: FTHS_CP5_PM_Reclaimed
    "fths_cp5_ah_lost" text, -- source: FTHS_CP5_AH_Lost
    "fths_cp5_ah_reclaimed" text, -- source: FTHS_CP5_AH_Reclaimed
    "fths_cp5_pd_lost" text, -- source: FTHS_CP5_PD_Lost
    "fths_cp5_pd_reclaimed" text, -- source: FTHS_CP5_PD_Reclaimed
    "fths_cp10_pm_lost" text, -- source: FTHS_CP10_PM_Lost
    "fths_cp10_pm_reclaimed" text, -- source: FTHS_CP10_PM_Reclaimed
    "fths_cp10_ah_lost" text, -- source: FTHS_CP10_AH_Lost
    "fths_cp10_ah_reclaimed" text, -- source: FTHS_CP10_AH_Reclaimed
    "fths_cp10_pd_lost" text, -- source: FTHS_CP10_PD_Lost
    "fths_cp10_pd_reclaimed" text, -- source: FTHS_CP10_PD_Reclaimed
    "fthv_eventdatekey" text, -- source: FTHV_EventDateKey
    "fthv_eventtimestamp" text, -- source: FTHV_EventTimestamp
    "fthv_direction" text, -- source: FTHV_Direction
    "fthv_cp1_open" text, -- source: FTHV_CP1_Open
    "fthv_cp1_high" text, -- source: FTHV_CP1_High
    "fthv_cp1_low" text, -- source: FTHV_CP1_Low
    "fthv_cp1_close" text, -- source: FTHV_CP1_Close
    "fthv_cp1_rth_vwap" text, -- source: FTHV_CP1_RTH_VWAP
    "fthv_cp1_vwap_state" text, -- source: FTHV_CP1_VWAP_State
    "fthv_cp1_vwap_lost" text, -- source: FTHV_CP1_VWAP_Lost
    "fthv_cp1_vwap_reclaimed" text, -- source: FTHV_CP1_VWAP_Reclaimed
    "fthv_cp1_wrongsideclosecount" text, -- source: FTHV_CP1_WrongSideCloseCount
    "fthv_cp1_maxwrongsidestreak" text, -- source: FTHV_CP1_MaxWrongSideStreak
    "fthv_has_cp1" text, -- source: FTHV_Has_CP1
    "fthv_cp2_open" text, -- source: FTHV_CP2_Open
    "fthv_cp2_high" text, -- source: FTHV_CP2_High
    "fthv_cp2_low" text, -- source: FTHV_CP2_Low
    "fthv_cp2_close" text, -- source: FTHV_CP2_Close
    "fthv_cp2_rth_vwap" text, -- source: FTHV_CP2_RTH_VWAP
    "fthv_cp2_vwap_state" text, -- source: FTHV_CP2_VWAP_State
    "fthv_cp2_vwap_lost" text, -- source: FTHV_CP2_VWAP_Lost
    "fthv_cp2_vwap_reclaimed" text, -- source: FTHV_CP2_VWAP_Reclaimed
    "fthv_cp2_wrongsideclosecount" text, -- source: FTHV_CP2_WrongSideCloseCount
    "fthv_cp2_maxwrongsidestreak" text, -- source: FTHV_CP2_MaxWrongSideStreak
    "fthv_has_cp2" text, -- source: FTHV_Has_CP2
    "fthv_cp3_open" text, -- source: FTHV_CP3_Open
    "fthv_cp3_high" text, -- source: FTHV_CP3_High
    "fthv_cp3_low" text, -- source: FTHV_CP3_Low
    "fthv_cp3_close" text, -- source: FTHV_CP3_Close
    "fthv_cp3_rth_vwap" text, -- source: FTHV_CP3_RTH_VWAP
    "fthv_cp3_vwap_state" text, -- source: FTHV_CP3_VWAP_State
    "fthv_cp3_vwap_lost" text, -- source: FTHV_CP3_VWAP_Lost
    "fthv_cp3_vwap_reclaimed" text, -- source: FTHV_CP3_VWAP_Reclaimed
    "fthv_cp3_wrongsideclosecount" text, -- source: FTHV_CP3_WrongSideCloseCount
    "fthv_cp3_maxwrongsidestreak" text, -- source: FTHV_CP3_MaxWrongSideStreak
    "fthv_has_cp3" text, -- source: FTHV_Has_CP3
    "fthv_cp5_open" text, -- source: FTHV_CP5_Open
    "fthv_cp5_high" text, -- source: FTHV_CP5_High
    "fthv_cp5_low" text, -- source: FTHV_CP5_Low
    "fthv_cp5_close" text, -- source: FTHV_CP5_Close
    "fthv_cp5_rth_vwap" text, -- source: FTHV_CP5_RTH_VWAP
    "fthv_cp5_vwap_state" text, -- source: FTHV_CP5_VWAP_State
    "fthv_cp5_vwap_lost" text, -- source: FTHV_CP5_VWAP_Lost
    "fthv_cp5_vwap_reclaimed" text, -- source: FTHV_CP5_VWAP_Reclaimed
    "fthv_cp5_wrongsideclosecount" text, -- source: FTHV_CP5_WrongSideCloseCount
    "fthv_cp5_maxwrongsidestreak" text, -- source: FTHV_CP5_MaxWrongSideStreak
    "fthv_has_cp5" text, -- source: FTHV_Has_CP5
    "fthv_cp10_open" text, -- source: FTHV_CP10_Open
    "fthv_cp10_high" text, -- source: FTHV_CP10_High
    "fthv_cp10_low" text, -- source: FTHV_CP10_Low
    "fthv_cp10_close" text, -- source: FTHV_CP10_Close
    "fthv_cp10_rth_vwap" text, -- source: FTHV_CP10_RTH_VWAP
    "fthv_cp10_vwap_state" text, -- source: FTHV_CP10_VWAP_State
    "fthv_cp10_vwap_lost" text, -- source: FTHV_CP10_VWAP_Lost
    "fthv_cp10_vwap_reclaimed" text, -- source: FTHV_CP10_VWAP_Reclaimed
    "fthv_cp10_wrongsideclosecount" text, -- source: FTHV_CP10_WrongSideCloseCount
    "fthv_cp10_maxwrongsidestreak" text, -- source: FTHV_CP10_MaxWrongSideStreak
    "fthv_has_cp10" text, -- source: FTHV_Has_CP10
    "eventdt" text -- source: EventDT
);

comment on table public.fthc_historical_staging_v1 is
'Temporary raw CSV staging table for FTHC 30M historical bootstrap. All source fields stored as text; normalization occurs server-side.';