import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../lib/supabase/server";
import styles from "./trade-review.module.css";

export const dynamic = "force-dynamic";
type Trade={trade_review_id:string;trade_number:number|null;trade_date:string;symbol:string;strategy_version:string;direction:string;signal_grade:string|null;entry_time:string|null;exit_time:string|null;realized_pnl_pct:number|null;strategy_outcome:string|null;trader_outcome:string|null;holding_seconds:number|null;review_status:string;key_lesson:string|null;metadata_json:Record<string,unknown>};
type Finding={finding_id:string;trade_review_id:string;category:string;title:string;finding:string;evidence_state:string;polarity:string|null;research_status:string;tags:string[]};
type Profile={profile_item_id:string;name:string;category:string;polarity:string;evidence_state:string;established:boolean;active:boolean;description:string|null;corrective_principle:string|null;supporting_trade_count:number};
type Evidence={profile_evidence_id:string;profile_item_id:string;trade_review_id:string|null;evidence_direction:string;evidence_note:string;evidence_weight:number|null};
const pct=(v:number|null|undefined,d=3)=>v==null?"—":`${v>0?"+":""}${Number(v).toFixed(d)}%`;
const pretty=(v:string|null|undefined)=>v?String(v).replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()):"—";
const duration=(s:number|null)=>s==null?"—":s<3600?`${Math.round(s/60)}m`:`${Math.floor(s/3600)}h ${Math.round((s%3600)/60)}m`;
const ct=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit",timeZone:"America/Chicago",timeZoneName:"short"}).format(new Date(v)):"—";
const metaNum=(t:Trade,...keys:string[])=>{for(const key of keys){const v=t.metadata_json?.[key];if(typeof v==="number")return Number(v)}return null};

export default async function MyTradeReviews(){
 const supabase=await createClient(); const {data:c,error:ce}=await supabase.auth.getClaims(); if(ce||!c?.claims)redirect("/login"); const {data:a,error:ae}=await supabase.rpc("is_trading_research_web_user"); if(ae||a!==true)redirect("/unauthorized");
 const [tr,fr,pr,er]=await Promise.all([
  supabase.from("trade_reviews").select("trade_review_id,trade_number,trade_date,symbol,strategy_version,direction,signal_grade,entry_time,exit_time,realized_pnl_pct,strategy_outcome,trader_outcome,holding_seconds,review_status,key_lesson,metadata_json").order("trade_number"),
  supabase.from("trade_review_findings").select("finding_id,trade_review_id,category,title,finding,evidence_state,polarity,research_status,tags").order("created_at",{ascending:false}),
  supabase.from("trader_profile_items").select("profile_item_id,name,category,polarity,evidence_state,established,active,description,corrective_principle,supporting_trade_count").eq("active",true).order("supporting_trade_count",{ascending:false}),
  supabase.from("trader_profile_evidence").select("profile_evidence_id,profile_item_id,trade_review_id,evidence_direction,evidence_note,evidence_weight")
 ]);
 const error=tr.error||fr.error||pr.error||er.error; const trades=(tr.data??[]) as Trade[]; const findings=(fr.data??[]) as Finding[]; const profiles=(pr.data??[]) as Profile[]; const evidence=(er.data??[]) as Evidence[];
 const complete=trades.filter(t=>t.review_status==="complete"); const wins=complete.filter(t=>Number(t.realized_pnl_pct)>0); const losses=complete.filter(t=>Number(t.realized_pnl_pct)<0); const pnls=complete.map(t=>Number(t.realized_pnl_pct??0)); const total=pnls.reduce((a,b)=>a+b,0); const avgWin=wins.length?wins.reduce((a,t)=>a+Number(t.realized_pnl_pct),0)/wins.length:null; const avgLoss=losses.length?losses.reduce((a,t)=>a+Number(t.realized_pnl_pct),0)/losses.length:null;
 const sessions=Object.entries(complete.reduce((m,t)=>{(m[t.trade_date]??=[]).push(t);return m;},{} as Record<string,Trade[]>)).sort(([a],[b])=>b.localeCompare(a)); const tradeById=new Map(trades.map(t=>[t.trade_review_id,t]));
 const strengths=profiles.filter(p=>p.polarity==="strength"); const priorities=profiles.filter(p=>p.polarity!=="strength"); const evidenceTrades=(p:Profile)=>evidence.filter(e=>e.profile_item_id===p.profile_item_id&&e.trade_review_id).map(e=>tradeById.get(e.trade_review_id!)).filter(Boolean) as Trade[];
 const gradeGroups=Object.entries(complete.filter(t=>t.signal_grade).reduce((m,t)=>{(m[t.signal_grade!]??=[]).push(t);return m;},{} as Record<string,Trade[]>)); const avgSecs=(xs:Trade[])=>xs.length?xs.reduce((a,t)=>a+(t.holding_seconds??0),0)/xs.length:null;
 const mfe=complete.map(t=>metaNum(t,"mfe_pct","mfe_approx_pct","post_exit_mfe_approx_pct")).filter((v):v is number=>v!=null); const mae=complete.map(t=>metaNum(t,"mae_pct","mae_approx_pct")).filter((v):v is number=>v!=null);
 return <main className={styles.tradeTheme}>
  <section className={`projectHero ${styles.hero}`}><div><Link className="backLink" href="/dashboard#trade-reviews-analysis">← Trade Reviews and Analysis</Link><p className={`eyebrow ${styles.accent}`}>RESULTS · TRADER DEVELOPMENT</p><h1>My Trade Reviews</h1><p className="lede">Performance, reviewed trades, sessions, trader profile, lessons and emerging patterns.</p><p className="sectionDescription">Trade → Evidence → Finding → Pattern → Corrective Action → Measurement → Improvement</p></div><Link className="projectLink" href="/dashboard/trade_review/tool">Open Tool Development →</Link></section>
  {error?<section className="alertPanel"><strong>Trade Review query failed.</strong><span>{error.message}</span></section>:<>
  <nav className={`projectNav ${styles.nav}`} aria-label="My Trade Reviews sections"><a href="#overview">Overview</a><a href="#log">Trade Log</a><a href="#sessions">Sessions</a><a href="#profile">Trader Profile</a><a href="#research">Research &amp; Patterns</a></nav>
  <section id="overview" className="metricGrid"><article className="metricCard"><span>Reviewed Trades</span><strong>{complete.length}</strong><small>Completed sample size</small></article><article className="metricCard"><span>Win Rate</span><strong>{complete.length?(wins.length/complete.length*100).toFixed(1):"—"}%</strong><small>{wins.length} wins · {losses.length} losses</small></article><article className="metricCard"><span>Cumulative P&amp;L</span><strong className={total>=0?styles.positive:styles.negative}>{pct(total)}</strong><small>Canonical percentage return</small></article><article className="metricCard"><span>Average Winner</span><strong className={styles.positive}>{pct(avgWin)}</strong><small>{wins.length} winners</small></article><article className="metricCard"><span>Average Loser</span><strong className={styles.negative}>{pct(avgLoss)}</strong><small>{losses.length} losers</small></article><article className="metricCard"><span>MFE / MAE Coverage</span><strong className="metricText">{mfe.length} / {mae.length}</strong><small>Structured measurements available</small></article></section>
  <section className={styles.sampleNote}><strong>PRELIMINARY DATA · SAMPLE SIZE: N = {complete.length}</strong><span>Evidence maturity is descriptive and can move forward or backward as new trades are reviewed.</span></section>

  <section className="projectSection" id="log"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>TRADE LOG</p><h2>Reviewed trades</h2></div><span>{complete.length} completed</span></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>#</th><th>Date</th><th>Symbol</th><th>Strategy</th><th>Grade</th><th>Direction</th><th>Entry</th><th>Hold</th><th>Strategy Outcome</th><th>Trader Outcome</th><th>P&amp;L</th><th>Major Finding</th></tr></thead><tbody>{complete.map(t=><tr key={t.trade_review_id}><td><Link href={`/dashboard/trade_review/${t.trade_review_id}`}>#{String(t.trade_number??"").padStart(3,"0")}</Link></td><td>{t.trade_date}</td><td><strong>{t.symbol}</strong></td><td>{t.strategy_version}</td><td>{t.signal_grade??"—"}</td><td>{pretty(t.direction)}</td><td>{ct(t.entry_time)}</td><td>{duration(t.holding_seconds)}</td><td className={styles.longCell}>{t.strategy_outcome??"—"}</td><td className={styles.longCell}>{t.trader_outcome??"—"}</td><td className={Number(t.realized_pnl_pct)>=0?styles.positive:styles.negative}><strong>{pct(t.realized_pnl_pct)}</strong></td><td className={styles.longCell}>{t.key_lesson??"—"}</td></tr>)}</tbody></table></div></section>

  <section className="projectSection" id="sessions"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>SESSIONS</p><h2>Daily reviewed performance</h2></div><span>{sessions.length} sessions</span></div><div className="stackList">{sessions.map(([date,ts])=>{let run=0,peak=0;ts.forEach(t=>{run+=Number(t.realized_pnl_pct??0);peak=Math.max(peak,run)});const sw=ts.filter(t=>Number(t.realized_pnl_pct)>0).length;const held=ts.filter(t=>t.holding_seconds!=null);return <article className="detailPanel" key={date}><div className="listTop"><strong>{date}</strong><span className={run>=0?styles.positive:styles.negative}>{pct(run)}</span></div><div className={styles.sessionStats}><span>{ts.length} trades</span><span>{sw}W / {ts.length-sw}L</span><span>Peak: {pct(peak)}</span><span>Giveback: {pct(Math.min(0,run-peak))}</span><span>Grades: {ts.map(t=>t.signal_grade??"—").join(", ")}</span><span>Avg hold: {duration(held.length?Math.round(held.reduce((a,t)=>a+(t.holding_seconds??0),0)/held.length):null)}</span></div></article>})}</div></section>

  <section className="projectSection" id="profile"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>PRELIMINARY TRADER PROFILE</p><h2>Evidence-backed development profile</h2></div><span>Sample Size: N = {complete.length}</span></div><div className="statusPlanGrid"><div><h3>Strengths</h3><div className="stackList">{strengths.slice(0,3).map(p=><article className="detailPanel" key={p.profile_item_id}><div className="listTop"><strong>{p.name}</strong><span className="statusPill">{pretty(p.evidence_state)}</span></div><p>{p.description}</p><small>{p.supporting_trade_count} supporting trade{p.supporting_trade_count===1?"":"s"}: {evidenceTrades(p).map(t=>`#${t.trade_number} ${t.symbol}`).join(", ")||"No linked trade evidence"}</small></article>)}</div></div><div><h3>Focus Areas</h3><div className="stackList">{priorities.slice(0,3).map(p=><article className="detailPanel" key={p.profile_item_id}><div className="listTop"><strong>{p.name}</strong><span className="statusPill">{pretty(p.evidence_state)}</span></div><p>{p.description}</p><small>{p.supporting_trade_count} supporting trade{p.supporting_trade_count===1?"":"s"}: {evidenceTrades(p).map(t=>`#${t.trade_number} ${t.symbol}`).join(", ")||"No linked trade evidence"}</small>{p.corrective_principle&&<p className={styles.principle}>{p.corrective_principle}</p>}</article>)}</div></div></div></section>

  <section className="projectSection" id="research"><div className="sectionHeader"><div><p className={`eyebrow ${styles.accent}`}>RESEARCH &amp; PATTERNS</p><h2>Evidence generated by reviewed trades</h2></div><span>{findings.length} findings</span></div><div className="statusPlanGrid"><article className="detailPanel"><span className="fieldLabel">Winner vs Loser Management</span><h3>Holding-time evidence</h3><dl className="detailGrid"><div><dt>Avg winner hold</dt><dd>{duration(avgSecs(wins.filter(t=>t.holding_seconds!=null)))}</dd></div><div><dt>Avg loser hold</dt><dd>{duration(avgSecs(losses.filter(t=>t.holding_seconds!=null)))}</dd></div></dl><p className="sectionDescription">Descriptive only until the sample supports a stronger conclusion.</p></article><article className="detailPanel"><span className="fieldLabel">Setup Quality</span><h3>Performance by grade</h3>{gradeGroups.length?gradeGroups.map(([g,ts])=><div className={styles.gradeRow} key={g}><strong>{g}</strong><span>{ts.length} trade{ts.length===1?"":"s"}</span><span>{pct(ts.reduce((a,t)=>a+Number(t.realized_pnl_pct??0),0)/ts.length)}</span><span>{Math.round(ts.filter(t=>Number(t.realized_pnl_pct)>0).length/ts.length*100)}% win</span></div>):<p>No setup grades recorded.</p>}</article></div><div className={styles.findingsGrid} style={{marginTop:18}}>{findings.map(f=>{const t=tradeById.get(f.trade_review_id);return <article className="detailPanel" key={f.finding_id}><div className="listTop"><strong>{f.title}</strong><span className="statusPill">{pretty(f.evidence_state)}</span></div><small>{pretty(f.category)}{t?` · #${t.trade_number} ${t.symbol}`:""} · {pretty(f.research_status)}</small><p>{f.finding}</p>{t&&<Link className={styles.tradeLink} href={`/dashboard/trade_review/${t.trade_review_id}`}>Open supporting trade →</Link>}</article>})}</div></section>
  </>}
 </main>;
}
