import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../lib/supabase/server";

export const dynamic = "force-dynamic";
type Strategy = { strategy_id:string; strategy_code:string; strategy_name:string; strategy_type:string; status:string; baseline_model:string|null; description:string|null; };
type ProjectState = { strategy_id:string; active_phase_code:string|null; active_phase_name:string|null; next_phase_code:string|null; next_phase_name:string|null; blocker_count:number|null; baseline_model:string|null; baseline_status:string|null; forward_validation_status:string|null; historical_dataset_status:string|null; last_decision:string|null; roadmap_version:string|null; updated_at:string|null; };
type Dataset = { strategy_id:string; is_frozen:boolean|null; };
type Phase = { strategy_id:string; phase_code:string; phase_name:string; sequence_order:number|null; status:string|null; };
type Review = { trade_review_id:string; realized_pnl_pct:number|null; review_status:string; };
type Profile = { profile_item_id:string; name:string; polarity:string; evidence_state:string; established:boolean; active:boolean; supporting_trade_count:number; };
type ComputeProvider = { provider_code:string; provider_name:string; provider_class:string|null; routing_priority:number; routing_role:string; configured_status:string; free_compute_status:string; quota_status:string; usage_status:string; incremental_spend_policy:string; spend_approval_required:boolean; paid_fallback_enabled:boolean; policy_summary:string|null; telemetry_source:string|null; last_telemetry_at:string|null; notes:string|null; updated_at:string|null; };
function prettyStatus(v:string|null|undefined){ if(!v)return "Not tracked"; return v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()); }
function formatUpdated(v:string|null|undefined){ if(!v)return "No state timestamp"; return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Chicago",timeZoneName:"short"}).format(new Date(v)); }
function pct(v:number|null|undefined,d=2){ return v==null?"—":`${v>0?"+":""}${Number(v).toFixed(d)}%`; }
function computeRole(v:string){ return v==="PRIMARY"?"Primary":v==="SECONDARY_OVERFLOW"?"Secondary / Overflow":prettyStatus(v); }

export default async function DashboardPage(){
 const supabase=await createClient(); const {data:claimsData,error:claimsError}=await supabase.auth.getClaims(); if(claimsError||!claimsData?.claims)redirect("/login");
 const {data:allowed,error:accessError}=await supabase.rpc("is_trading_research_web_user"); if(accessError||allowed!==true)redirect("/unauthorized");
 const [strategiesResult,statesResult,datasetsResult,phasesResult,reviewsResult,profilesResult,computeResult]=await Promise.all([
  supabase.from("strategies").select("strategy_id,strategy_code,strategy_name,strategy_type,status,baseline_model,description").order("strategy_name"),
  supabase.from("project_state").select("strategy_id,active_phase_code,active_phase_name,next_phase_code,next_phase_name,blocker_count,baseline_model,baseline_status,forward_validation_status,historical_dataset_status,last_decision,roadmap_version,updated_at"),
  supabase.from("datasets").select("strategy_id,is_frozen"),
  supabase.from("program_phases").select("strategy_id,phase_code,phase_name,sequence_order,status").order("sequence_order"),
  supabase.from("trade_reviews").select("trade_review_id,realized_pnl_pct,review_status"),
  supabase.from("trader_profile_items").select("profile_item_id,name,polarity,evidence_state,established,active,supporting_trade_count").eq("active",true).order("supporting_trade_count",{ascending:false}),
  supabase.from("v_compute_provider_status").select("provider_code,provider_name,provider_class,routing_priority,routing_role,configured_status,free_compute_status,quota_status,usage_status,incremental_spend_policy,spend_approval_required,paid_fallback_enabled,policy_summary,telemetry_source,last_telemetry_at,notes,updated_at").order("routing_priority",{ascending:true})
 ]);
 const queryError=strategiesResult.error||statesResult.error||datasetsResult.error||phasesResult.error||reviewsResult.error||profilesResult.error||computeResult.error;
 const strategies=(strategiesResult.data??[]) as Strategy[]; const states=(statesResult.data??[]) as ProjectState[]; const datasets=(datasetsResult.data??[]) as Dataset[]; const phases=(phasesResult.data??[]) as Phase[];
 const reviews=(reviewsResult.data??[]) as Review[]; const profiles=(profilesResult.data??[]) as Profile[]; const computeProviders=(computeResult.data??[]) as ComputeProvider[];
 const stateByStrategy=new Map(states.map(s=>[s.strategy_id,s])); const datasetStats=new Map<string,{total:number;frozen:number}>(); for(const d of datasets){const x=datasetStats.get(d.strategy_id)??{total:0,frozen:0};x.total++;if(d.is_frozen)x.frozen++;datasetStats.set(d.strategy_id,x);}
 const phasesByStrategy=new Map<string,Phase[]>(); for(const p of phases){const x=phasesByStrategy.get(p.strategy_id)??[];x.push(p);phasesByStrategy.set(p.strategy_id,x);}
 const blockerCount=states.reduce((n,s)=>n+(s.blocker_count??0),0);
 const masterCodes=new Set(["INTRADAY_OPP_MASTER"]); const tradeReviewCodes=new Set(["TRADE_REVIEW"]); const infrastructureCodes=new Set(["CLOUD_COMPUTE","PLATFORM","WEB_APP"]); const toolCodes=new Set(["REALTIME_ADVISOR","TV_AUTOMATION","PREMARKET_SCANNER"]);
 const isChildResearchLane=(code:string)=>/^IR\d{2}_/.test(code);
 const masterPrograms=strategies.filter(s=>masterCodes.has(s.strategy_code)); const childResearchLanes=strategies.filter(s=>isChildResearchLane(s.strategy_code)); const tradeReviews=strategies.filter(s=>tradeReviewCodes.has(s.strategy_code)); const infrastructure=strategies.filter(s=>infrastructureCodes.has(s.strategy_code)); const tools=strategies.filter(s=>toolCodes.has(s.strategy_code)); const tradingSystems=strategies.filter(s=>!masterCodes.has(s.strategy_code)&&!isChildResearchLane(s.strategy_code)&&!tradeReviewCodes.has(s.strategy_code)&&!infrastructureCodes.has(s.strategy_code)&&!toolCodes.has(s.strategy_code));
 const completed=reviews.filter(r=>r.review_status==="complete"&&r.realized_pnl_pct!=null); const wins=completed.filter(r=>Number(r.realized_pnl_pct)>0); const losses=completed.filter(r=>Number(r.realized_pnl_pct)<0); const totalPnl=completed.reduce((n,r)=>n+Number(r.realized_pnl_pct??0),0); const avgWinner=wins.length?wins.reduce((n,r)=>n+Number(r.realized_pnl_pct),0)/wins.length:null; const avgLoser=losses.length?losses.reduce((n,r)=>n+Number(r.realized_pnl_pct),0)/losses.length:null;
 const strengths=profiles.filter(p=>p.polarity==="strength").slice(0,2); const focusAreas=profiles.filter(p=>p.polarity!=="strength").slice(0,2); const tradeReviewProject=tradeReviews[0]; const tradeReviewState=tradeReviewProject?stateByStrategy.get(tradeReviewProject.strategy_id):undefined;
 const roadmapSnapshot=(strategy:Strategy,state:ProjectState|undefined)=>{const all=phasesByStrategy.get(strategy.strategy_id)??[];if(!all.length)return null;let current=all.findIndex(p=>p.phase_code===state?.active_phase_code);if(current<0)current=all.findIndex(p=>p.status==="active");if(current<0)return null;const start=Math.max(0,current-2);const end=Math.min(all.length,current+3);return <div className="roadmapSnapshot"><span className="fieldLabel">Roadmap snapshot</span><div className="roadmapSteps">{all.slice(start,end).map((p,i)=>{const idx=start+i;const isCurrent=idx===current;const isPast=idx<current;return <span className={`roadmapStep ${isCurrent?"roadmapStepCurrent":isPast?"roadmapStepPast":"roadmapStepFuture"}`} key={p.phase_code}>{isPast?"✓ ":isCurrent?"● ":""}{p.phase_code}<small>{p.phase_name}</small></span>})}</div></div>};
 const renderCard=(strategy:Strategy)=>{const state=stateByStrategy.get(strategy.strategy_id);const stats=datasetStats.get(strategy.strategy_id)??{total:0,frozen:0};return <article className="strategyCard" key={strategy.strategy_id}><div className="cardTopline"><span className="strategyCode">{strategy.strategy_code}</span><span className={`statusPill status-${strategy.status}`}>{prettyStatus(strategy.status)}</span></div><h3>{strategy.strategy_name}</h3><p className="strategyDescription">{strategy.description??"No description recorded."}</p><div className="phaseBlock"><span className="fieldLabel">Current phase</span><strong>{state?.active_phase_code??"—"}{state?.active_phase_name?` · ${state.active_phase_name}`:""}</strong><span className="nextPhase">Next: {state?.next_phase_code??"Not scheduled"}{state?.next_phase_name?` · ${state.next_phase_name}`:""}</span></div>{roadmapSnapshot(strategy,state)}<dl className="detailGrid"><div><dt>Baseline</dt><dd>{state?.baseline_model??strategy.baseline_model??"Not set"}</dd></div><div><dt>Baseline status</dt><dd>{prettyStatus(state?.baseline_status)}</dd></div><div><dt>Forward validation</dt><dd>{prettyStatus(state?.forward_validation_status)}</dd></div><div><dt>Datasets</dt><dd>{stats.total}{stats.total?` (${stats.frozen} frozen)`:""}</dd></div><div><dt>Roadmap</dt><dd>{state?.roadmap_version??"Not tracked"}</dd></div><div><dt>Blockers</dt><dd>{state?.blocker_count??0}</dd></div></dl><div className="decisionBlock"><span className="fieldLabel">Latest recorded decision</span><p>{state?.last_decision??"No project-state decision summary recorded yet."}</p></div><footer className="cardFooter"><span>{state?.historical_dataset_status?`Data: ${state.historical_dataset_status}`:"Historical data status not tracked"}</span><time>Updated: {formatUpdated(state?.updated_at)}</time></footer><Link className="projectLink" href={`/dashboard/${strategy.strategy_code.toLowerCase()}`}>View status, plan & roadmap →</Link></article>};
 const renderGroup=(id:string,eyebrow:string,title:string,description:string,items:Strategy[],tone:string)=><section id={id} className={`portfolioSection ${tone}`}><div className="sectionHeader"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="sectionDescription">{description}</p></div><span>{items.length} project{items.length===1?"":"s"}</span></div><div className="strategyGrid">{items.map(renderCard)}</div></section>;
 const summaryCard=(href:string,label:string,value:number,detail:string)=><a className="metricCard" style={{textDecoration:"none"}} href={href}><span>{label}</span><strong>{value}</strong><small>{detail}</small></a>;
 return <main><section className="dashboardHero"><div><p className="eyebrow">TRADING INTELLIGENCE PLATFORM</p><h1>Platform Control Center</h1><p className="lede">A unified platform for trading research, system development, validation, decision support, infrastructure, and operational intelligence.</p></div><form action="/auth/signout" method="post"><button className="secondaryButton" type="submit">Sign out</button></form></section>
 <section className="trackingHealth trackingHealth-ok"><div><span className="fieldLabel">HOMEPAGE HIERARCHY V2 PREVIEW</span><strong>Production remains unchanged</strong></div><p>This preview simplifies the homepage into five peer domains: Research, Trading Systems, Trading Tools, Trade Reviews &amp; Analysis, and Platform Infrastructure.</p></section>
 {queryError?<section className="alertPanel"><strong>Dashboard query failed.</strong><span>{queryError.message}</span></section>:<><section className="sectionHeader"><div><p className="eyebrow">PLATFORM SNAPSHOT</p><h2>What needs attention</h2><p className="sectionDescription">A compact operational snapshot; navigation lives in the domain sections below.</p></div><span className="securityBadge">Authenticated · Allowlisted · Read-only</span></section><section className="metricGrid">{summaryCard("#research","Research Lanes",childResearchLanes.length,"Independent opportunity research")}{summaryCard("#trading-systems","Trading Systems",tradingSystems.length,"Indicators and strategy systems")}{summaryCard("#trading-tools","Trading Tools",tools.length,"Advisory and execution support")}{summaryCard("#trade-reviews-analysis","Reviewed Trades",completed.length,"Trader development evidence")}{summaryCard("#platform-infrastructure","Infrastructure",infrastructure.length,"Shared platform services")}{summaryCard("#research","Open Blockers",blockerCount,"Across tracked project states")}</section>

 <section id="research" className="portfolioSection portfolioMaster"><div className="sectionHeader"><div><p className="eyebrow">RESEARCH</p><h2>Research</h2><p className="sectionDescription">Master research programs coordinate independent evidence-generating lanes. Control-plane mechanics remain available inside each program without adding another homepage hierarchy layer.</p></div><span>{masterPrograms.length} master program{masterPrograms.length===1?"":"s"} · {childResearchLanes.length} lane{childResearchLanes.length===1?"":"s"}</span></div>
  <div className="sectionHeader" style={{marginTop:24}}><div><p className="eyebrow">MASTER RESEARCH PROGRAMS</p><h2>Master Research Programs</h2></div></div>
  <div className="strategyGrid">{masterPrograms.map(program=>{const state=stateByStrategy.get(program.strategy_id);return <article className="strategyCard" key={program.strategy_id}><div className="cardTopline"><span className="strategyCode">PROGRAM · {program.strategy_code}</span><span className="statusPill">{prettyStatus(program.status)}</span></div><h3>Intraday 0.5%–1.0% Opportunity Discovery</h3><p className="strategyDescription">{program.description}</p><div className="phaseBlock"><span className="fieldLabel">Current master phase</span><strong>{state?.active_phase_code??"—"} · {state?.active_phase_name??"Not tracked"}</strong><span className="nextPhase">Next: {state?.next_phase_code??"—"} · {state?.next_phase_name??"Not tracked"}</span></div>{roadmapSnapshot(program,state)}<Link className="projectLink" href="/dashboard/intraday-opportunity-discovery">Open research program →</Link></article>})}</div>
  {childResearchLanes.length>0&&<><div className="sectionHeader" style={{marginTop:30}}><div><p className="eyebrow">RESEARCH LANES</p><h2>Research Lanes</h2></div></div><div className="strategyGrid">{childResearchLanes.map(renderCard)}</div></>}
 </section>

 {renderGroup("trading-systems","TRADING SYSTEMS","Trading Systems","TradingView indicators, strategy research, validation, and model development.",tradingSystems,"portfolioIndicators")}
 {renderGroup("trading-tools","TRADING TOOLS","Trading Tools","Decision-support, advisory, scanning, and execution-support systems.",tools,"portfolioTools")}

 <section id="trade-reviews-analysis" className="portfolioSection portfolioTradeReviews"><div className="sectionHeader"><div><p className="eyebrow">TRADE REVIEWS & ANALYSIS</p><h2>Trade Reviews &amp; Analysis</h2><p className="sectionDescription">One connected system with two distinct experiences: trader results and development, plus the tool and research infrastructure that powers the reviews.</p></div><span className="securityBadge">Read-only operational data</span></div>
  <div className="metricGrid" style={{marginTop:18}}><article className="metricCard"><span>Reviewed Trades</span><strong>{completed.length}</strong><small>Completed reviews</small></article><article className="metricCard"><span>Win Rate</span><strong>{completed.length?(wins.length/completed.length*100).toFixed(1):"—"}%</strong><small>{wins.length} wins · {losses.length} losses</small></article><article className="metricCard"><span>Net Realized P&amp;L</span><strong>{pct(totalPnl)}</strong><small>Canonical percentage return</small></article><article className="metricCard"><span>Average Winner</span><strong>{pct(avgWinner)}</strong><small>{wins.length} winning trades</small></article><article className="metricCard"><span>Average Loser</span><strong>{pct(avgLoser)}</strong><small>{losses.length} losing trades</small></article></div>
  <div className="statusPlanGrid" style={{marginTop:20}}><article className="detailPanel"><p className="eyebrow">PRELIMINARY TRADER PROFILE</p><h3>Sample Size: N = {completed.length}</h3><div className="detailGrid"><div><dt>Strengths</dt><dd>{strengths.length?strengths.map(p=>`${p.name} · ${prettyStatus(p.evidence_state)}`).join("; "):"No active strength observations"}</dd></div><div><dt>Focus areas</dt><dd>{focusAreas.length?focusAreas.map(p=>`${p.name} · ${prettyStatus(p.evidence_state)}`).join("; "):"No active focus observations"}</dd></div></div><p className="sectionDescription">Evidence maturity remains visible and may strengthen, weaken, or reverse as new reviewed trades are added.</p></article><article className="detailPanel"><p className="eyebrow">CURRENT TOOL DEVELOPMENT</p><h3>{tradeReviewState?.active_phase_code??"—"}{tradeReviewState?.active_phase_name?` · ${tradeReviewState.active_phase_name}`:""}</h3><p>{tradeReviewState?.last_decision??"No current project-state summary recorded."}</p><small>Roadmap: {tradeReviewState?.roadmap_version??"Not tracked"}</small></article></div>
  <div className="strategyGrid" style={{marginTop:20}}><article className="strategyCard"><div className="cardTopline"><span className="strategyCode">RESULTS · TRADER DEVELOPMENT</span></div><h3>My Trade Reviews</h3><p className="strategyDescription">Performance, reviewed trades, sessions, trader profile, lessons and emerging patterns.</p><Link className="projectLink" href="/dashboard/trade_review">Open My Trade Reviews →</Link></article><article className="strategyCard"><div className="cardTopline"><span className="strategyCode">PROJECT · DEVELOPMENT</span></div><h3>Trade Review &amp; Analysis Tool</h3><p className="strategyDescription">Tool development, roadmap, methodology, Trade Health, Event Engine, Trader Development Engine and research infrastructure.</p><Link className="projectLink" href="/dashboard/trade_review/tool">Open Tool Development →</Link></article></div>
 </section>

 <section id="platform-infrastructure" className="portfolioSection portfolioInfrastructure"><div className="sectionHeader"><div><p className="eyebrow">PLATFORM INFRASTRUCTURE</p><h2>Platform Infrastructure</h2><p className="sectionDescription">The shared web application, market-data platform, compute, and execution infrastructure supporting every domain above.</p></div><span>{infrastructure.length} project{infrastructure.length===1?"":"s"}</span></div>
  <div className="strategyGrid">{infrastructure.map(renderCard)}</div>
  <div className="sectionHeader" style={{marginTop:30}}><div><p className="eyebrow">COMPUTE STATUS</p><h2>Free Compute Routing</h2><p className="sectionDescription">Live configuration status from the governed compute-provider database source. Quota marked Unverified means usage telemetry is not connected; it does not mean capacity is exhausted or unavailable.</p></div><span>{computeProviders.length} configured option{computeProviders.length===1?"":"s"}</span></div>
  <div className="strategyGrid">{computeProviders.map(provider=><article className="detailPanel" key={provider.provider_code}><div className="cardTopline"><div><span className="strategyCode">#{provider.routing_priority} · {computeRole(provider.routing_role)}</span><h3>{provider.provider_name}</h3></div><span className="statusPill status-active">{prettyStatus(provider.configured_status)}</span></div><div className="detailGrid"><div><dt>Compute status</dt><dd>{provider.free_compute_status==="FREE_COMPUTE_OPTION"?"Free Compute Option":prettyStatus(provider.free_compute_status)}</dd></div><div><dt>Quota</dt><dd>{provider.quota_status==="UNVERIFIED"?"Unverified · telemetry not connected":prettyStatus(provider.quota_status)}</dd></div><div><dt>Usage telemetry</dt><dd>{provider.usage_status==="TELEMETRY_NOT_CONNECTED"?"Not connected":prettyStatus(provider.usage_status)}</dd></div><div><dt>Spend approval</dt><dd>{provider.spend_approval_required?"Required before paid usage":"Not required for configured route"}</dd></div>{provider.telemetry_source&&<div><dt>Telemetry source</dt><dd>{provider.telemetry_source}</dd></div>}{provider.last_telemetry_at&&<div><dt>Last telemetry</dt><dd>{formatUpdated(provider.last_telemetry_at)}</dd></div>}</div><div className="decisionBlock"><span className="fieldLabel">Governing policy</span><p><strong>{prettyStatus(provider.incremental_spend_policy)}</strong></p><p>{provider.policy_summary??provider.notes??"No provider policy summary recorded."}</p>{provider.paid_fallback_enabled&&<small>Paid fallback is enabled in provider status.</small>}</div></article>)}</div>
  <footer className="cardFooter"><span>Routing: GitHub Actions → Cloud Run when appropriate and within policy → Local Windows fallback. Google Cloud Run configuration never authorizes paid execution without explicit approval.</span><span>Future telemetry fields are already supported for capacity, usage, warnings and refresh time.</span></footer>
 </section></>}</main>;
}
