import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../lib/supabase/server";

export const dynamic = "force-dynamic";
type Strategy = { strategy_id:string; strategy_code:string; strategy_name:string; strategy_type:string; status:string; baseline_model:string|null; description:string|null; };
type ProjectState = { strategy_id:string; active_phase_code:string|null; active_phase_name:string|null; next_phase_code:string|null; next_phase_name:string|null; blocker_count:number|null; baseline_model:string|null; baseline_status:string|null; forward_validation_status:string|null; historical_dataset_status:string|null; last_decision:string|null; roadmap_version:string|null; updated_at:string|null; };
type Dataset = { strategy_id:string; is_frozen:boolean|null; };
type Phase = { strategy_id:string; phase_code:string; phase_name:string; sequence_order:number|null; status:string|null; };
function prettyStatus(v:string|null|undefined){ if(!v)return "Not tracked"; return v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()); }
function formatUpdated(v:string|null|undefined){ if(!v)return "No state timestamp"; return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Chicago",timeZoneName:"short"}).format(new Date(v)); }

export default async function DashboardPage(){
 const supabase=await createClient(); const {data:claimsData,error:claimsError}=await supabase.auth.getClaims(); if(claimsError||!claimsData?.claims)redirect("/login");
 const {data:allowed,error:accessError}=await supabase.rpc("is_trading_research_web_user"); if(accessError||allowed!==true)redirect("/unauthorized");
 const [strategiesResult,statesResult,datasetsResult,phasesResult]=await Promise.all([
  supabase.from("strategies").select("strategy_id,strategy_code,strategy_name,strategy_type,status,baseline_model,description").order("strategy_name"),
  supabase.from("project_state").select("strategy_id,active_phase_code,active_phase_name,next_phase_code,next_phase_name,blocker_count,baseline_model,baseline_status,forward_validation_status,historical_dataset_status,last_decision,roadmap_version,updated_at"),
  supabase.from("datasets").select("strategy_id,is_frozen"),
  supabase.from("program_phases").select("strategy_id,phase_code,phase_name,sequence_order,status").order("sequence_order")]);
 const queryError=strategiesResult.error||statesResult.error||datasetsResult.error||phasesResult.error; const strategies=(strategiesResult.data??[]) as Strategy[]; const states=(statesResult.data??[]) as ProjectState[]; const datasets=(datasetsResult.data??[]) as Dataset[]; const phases=(phasesResult.data??[]) as Phase[];
 const stateByStrategy=new Map(states.map(s=>[s.strategy_id,s])); const datasetStats=new Map<string,{total:number;frozen:number}>(); for(const d of datasets){const x=datasetStats.get(d.strategy_id)??{total:0,frozen:0};x.total++;if(d.is_frozen)x.frozen++;datasetStats.set(d.strategy_id,x);}
 const phasesByStrategy=new Map<string,Phase[]>(); for(const p of phases){const x=phasesByStrategy.get(p.strategy_id)??[];x.push(p);phasesByStrategy.set(p.strategy_id,x);}
 const activeCount=strategies.filter(s=>s.status==="active").length; const researchCount=strategies.filter(s=>s.status==="research").length; const blockerCount=states.reduce((n,s)=>n+(s.blocker_count??0),0);
 const masterCodes=new Set(["INTRADAY_OPP_MASTER"]); const tradeReviewCodes=new Set(["TRADE_REVIEW"]); const infrastructureCodes=new Set(["CLOUD_COMPUTE"]); const toolCodes=new Set(["PLATFORM","REALTIME_ADVISOR","TV_AUTOMATION","PREMARKET_SCANNER"]);
 const isChildResearchLane=(code:string)=>/^IR\d{2}_/.test(code);
 const masterPrograms=strategies.filter(s=>masterCodes.has(s.strategy_code)); const childResearchLanes=strategies.filter(s=>isChildResearchLane(s.strategy_code)); const tradeReviews=strategies.filter(s=>tradeReviewCodes.has(s.strategy_code)); const infrastructure=strategies.filter(s=>infrastructureCodes.has(s.strategy_code)); const tools=strategies.filter(s=>toolCodes.has(s.strategy_code)); const indicatorStrategies=strategies.filter(s=>!masterCodes.has(s.strategy_code)&&!isChildResearchLane(s.strategy_code)&&!tradeReviewCodes.has(s.strategy_code)&&!infrastructureCodes.has(s.strategy_code)&&!toolCodes.has(s.strategy_code));
 const roadmapSnapshot=(strategy:Strategy,state:ProjectState|undefined)=>{const all=phasesByStrategy.get(strategy.strategy_id)??[];if(!all.length)return null;let current=all.findIndex(p=>p.phase_code===state?.active_phase_code);if(current<0)current=all.findIndex(p=>p.status==="active");if(current<0)return null;const start=Math.max(0,current-2);const end=Math.min(all.length,current+3);return <div className="roadmapSnapshot"><span className="fieldLabel">Roadmap snapshot</span><div className="roadmapSteps">{all.slice(start,end).map((p,i)=>{const idx=start+i;const isCurrent=idx===current;const isPast=idx<current;return <span className={`roadmapStep ${isCurrent?"roadmapStepCurrent":isPast?"roadmapStepPast":"roadmapStepFuture"}`} key={p.phase_code}>{isPast?"✓ ":isCurrent?"● ":""}{p.phase_code}<small>{p.phase_name}</small></span>})}</div></div>};
 const renderCard=(strategy:Strategy)=>{const state=stateByStrategy.get(strategy.strategy_id);const stats=datasetStats.get(strategy.strategy_id)??{total:0,frozen:0};return <article className="strategyCard" key={strategy.strategy_id}><div className="cardTopline"><span className="strategyCode">{strategy.strategy_code}</span><span className={`statusPill status-${strategy.status}`}>{prettyStatus(strategy.status)}</span></div><h3>{strategy.strategy_name}</h3><p className="strategyDescription">{strategy.description??"No description recorded."}</p><div className="phaseBlock"><span className="fieldLabel">Current phase</span><strong>{state?.active_phase_code??"—"}{state?.active_phase_name?` · ${state.active_phase_name}`:""}</strong><span className="nextPhase">Next: {state?.next_phase_code??"Not scheduled"}{state?.next_phase_name?` · ${state.next_phase_name}`:""}</span></div>{roadmapSnapshot(strategy,state)}<dl className="detailGrid"><div><dt>Baseline</dt><dd>{state?.baseline_model??strategy.baseline_model??"Not set"}</dd></div><div><dt>Baseline status</dt><dd>{prettyStatus(state?.baseline_status)}</dd></div><div><dt>Forward validation</dt><dd>{prettyStatus(state?.forward_validation_status)}</dd></div><div><dt>Datasets</dt><dd>{stats.total}{stats.total?` (${stats.frozen} frozen)`:""}</dd></div><div><dt>Roadmap</dt><dd>{state?.roadmap_version??"Not tracked"}</dd></div><div><dt>Blockers</dt><dd>{state?.blocker_count??0}</dd></div></dl><div className="decisionBlock"><span className="fieldLabel">Latest recorded decision</span><p>{state?.last_decision??"No project-state decision summary recorded yet."}</p></div><footer className="cardFooter"><span>{state?.historical_dataset_status?`Data: ${state.historical_dataset_status}`:"Historical data status not tracked"}</span><time>Updated: {formatUpdated(state?.updated_at)}</time></footer><Link className="projectLink" href={`/dashboard/${strategy.strategy_code.toLowerCase()}`}>View status, plan & roadmap →</Link></article>};
 const renderGroup=(eyebrow:string,title:string,description:string,items:Strategy[],tone:string)=><section className={`portfolioSection ${tone}`}><div className="sectionHeader"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="sectionDescription">{description}</p></div><span>{items.length} project{items.length===1?"":"s"}</span></div><div className="strategyGrid">{items.map(renderCard)}</div></section>;
 return <main><section className="dashboardHero"><div><p className="eyebrow">TRADING INTELLIGENCE PLATFORM</p><h1>Platform Control Center</h1><p className="lede">Live, protected status across master research programs, research lanes, indicators, strategies, tools, infrastructure, trade review, datasets, and validation work.</p></div><form action="/auth/signout" method="post"><button className="secondaryButton" type="submit">Sign out</button></form></section>
 {queryError?<section className="alertPanel"><strong>Dashboard query failed.</strong><span>{queryError.message}</span></section>:<><section className="metricGrid"><article className="metricCard"><span>Registered projects</span><strong>{strategies.length}</strong><small>{states.length} with project-state tracking</small></article><article className="metricCard"><span>Active systems</span><strong>{activeCount}</strong><small>{researchCount} additional projects in research</small></article><article className="metricCard"><span>Current blockers</span><strong>{blockerCount}</strong><small>Across tracked project states</small></article><article className="metricCard"><span>Protected datasets</span><strong>{datasets.length}</strong><small>{datasets.filter(d=>d.is_frozen).length} frozen datasets</small></article></section>
 <section className="sectionHeader"><div><p className="eyebrow">RESEARCH PROGRAMS</p><h2>Master control planes</h2><p className="sectionDescription">Programs coordinate independent research lanes and evidence. They are not individual trading systems.</p></div><span className="securityBadge">Authenticated · Allowlisted · Read-only</span></section>
 {masterPrograms.map(program=>{const state=stateByStrategy.get(program.strategy_id);return <section className="portfolioSection portfolioMaster" key={program.strategy_id}><div className="cardTopline"><span className="strategyCode">PROGRAM · {program.strategy_code}</span><span className="statusPill">{prettyStatus(program.status)}</span></div><h2 style={{marginTop:14,fontSize:30}}>Intraday 0.5%–1.0% Opportunity Discovery</h2><p className="sectionDescription">Master Research Coordination · {program.description}</p><div className="phaseBlock" style={{marginTop:18}}><span className="fieldLabel">Current master phase</span><strong>{state?.active_phase_code??"—"} · {state?.active_phase_name??"Not tracked"}</strong><span className="nextPhase">Roadmap: {state?.roadmap_version??"Not tracked"} · Next: {state?.next_phase_code??"—"} · {state?.next_phase_name??"Not tracked"}</span></div>{roadmapSnapshot(program,state)}<footer className="cardFooter"><span>Coordinates independent opportunity-family research; no profitability claims until validated results exist.</span><time>Updated: {formatUpdated(state?.updated_at)}</time></footer><Link className="projectLink" href="/dashboard/intraday-opportunity-discovery">Open Master Control Plane →</Link></section>})}
 {childResearchLanes.length>0&&renderGroup("RESEARCH LANES","Independent research lanes","Child research efforts coordinated by the Intraday Opportunity Discovery Master program. These are research hypotheses, not implementations.",childResearchLanes,"portfolioMaster")}
 <section className="sectionHeader" style={{marginTop:46}}><div><p className="eyebrow">PROJECT PORTFOLIO</p><h2>Platform systems</h2></div></section>{renderGroup("INDICATORS & STRATEGIES","Indicators & strategies","TradingView indicators, strategy research, validation, and model development.",indicatorStrategies,"portfolioIndicators")}{renderGroup("TOOLS","Tools","Research, decision-support, advisory, and execution-support systems.",tools,"portfolioTools")}{renderGroup("INFRASTRUCTURE","Infrastructure","Shared compute, data, and execution infrastructure supporting the Trading Intelligence Platform.",infrastructure,"portfolioInfrastructure")}{renderGroup("TRADE REVIEWS","Trade reviews","Executed-trade reconstruction, review, trade-health analysis, and trader-development research.",tradeReviews,"portfolioTradeReviews")}</>}</main>;
}
